"""empty message

Revision ID: 8f3f80382469
Revises: 75a87b832687
Create Date: 2023-08-14 02:58:28.162938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f3f80382469'
down_revision = '75a87b832687'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('car_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('users_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_reviews_users_id_users'), 'users', ['users_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_reviews_car_id_cars'), 'cars', ['car_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('password_hash', sa.String(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_users_email'), ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_email'), type_='unique')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('email')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_reviews_car_id_cars'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_reviews_users_id_users'), type_='foreignkey')
        batch_op.drop_column('users_id')
        batch_op.drop_column('car_id')

    # ### end Alembic commands ###
